name = "FD"
grammar = "fd"
path_suffixes = ["fd"]
line_comments = ["# "]
block_comment = []
tab_size = 2
hard_tabs = false
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
]
autoclose_before = ";:.,=}])>"
word_characters = ["@", "#"]

[lsp.fd-lsp]
format_on_save = "off"
